# --- Shell & editors ---
brew "fish"
brew "nano"
brew "stow"

# --- Dev languages & toolchains ---
brew "cmake"
brew "go"
brew "jdtls"
brew "maven"
brew "mise"
brew "ninja"
brew "pipx"
brew "uv"

# --- Containers & Kubernetes ---
brew "container"
brew "podman"
brew "docker"
brew "docker-compose"
brew "dive"
brew "kind"
brew "qemu"
brew "stern"

# --- Git & CI ---
brew "git"
brew "gh"
brew "lazygit"
brew "shellcheck"

# --- CLI utilities ---
brew "bat"
brew "eza"
brew "fd"
brew "fzf"
brew "ripgrep"
brew "jq"
brew "yq"
brew "tree"
brew "coreutils"
brew "moreutils"
brew "binutils"
brew "curl"
brew "wget"
brew "rsync"
brew "sevenzip"
brew "xz"
brew "watch"
brew "watchexec"
brew "just"
brew "duf"
brew "htop"
brew "glances"
brew "bandwhich"
brew "pstree"
brew "noti"
brew "qrencode"
brew "midnight-commander"
brew "netcat"

# --- HTTP & networking ---
brew "httpie"
brew "http-server"
brew "hey"
brew "wrk"
brew "websocat"
brew "hivemind"

# --- Document & media ---
brew "asciidoctor"
brew "pandoc"
brew "hugo"
brew "plantuml"
brew "graphviz"
brew "gnuplot"
brew "imagemagick"
brew "ffmpeg"
brew "flac"
brew "lame"
brew "typst"

# --- Security & crypto ---
brew "gnupg"
brew "pinentry-mac"
brew "aspell"

# --- AI & misc ---
brew "cowsay"
brew "fortune"
brew "ollama"
brew "yt-dlp"
brew "upx"
brew "vhs"
brew "ccache"
brew "pkgconf"

# --- Casks: apps ---
cask "1password"
cask "appcleaner"
cask "discord"
cask "ghostty"
cask "keepingyouawake"
cask "localsend"
cask "basictex"
cask "omnigraffle"
cask "podman-desktop"
cask "signal"
cask "skim"
cask "slack"
cask "utm"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
cask "wireshark-app"
cask "zulip"

# --- Casks: fonts ---
cask "font-bangers"
cask "font-cascadia-code"
cask "font-cousine"
cask "font-fira-code"
cask "font-fontawesome"
cask "font-handlee"
cask "font-hasklig"
cask "font-ibm-plex"
cask "font-inconsolata"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "font-linux-libertine"
cask "font-montserrat"
cask "font-noto-color-emoji"
cask "font-noto-emoji"
cask "font-noto-sans"
cask "font-noto-serif"
cask "font-open-sans"
cask "font-redhat"
cask "font-roboto"
cask "font-roboto-mono"
cask "font-roboto-slab"
cask "font-signika-negative"
cask "font-source-code-pro"
cask "font-source-sans-3"
cask "font-source-serif-4"
cask "font-ubuntu"
cask "font-yanone-kaffeesatz"
