#Modified by Testcontainers
#Tue Apr 02 18:56:29 CEST 2024
docker.client.strategy=org.testcontainers.dockerclient.UnixSocketClientProviderStrategy
ryuk.container.privileged=true
testcontainers.reuse.enable=false
