#Modified by Testcontainers
#Thu Aug 01 15:08:21 CEST 2024
docker.client.strategy=org.testcontainers.dockerclient.UnixSocketClientProviderStrategy
ryuk.container.privileged=true
testcontainers.reuse.enable=false
