#Modified by Testcontainers
#Mon Sep 14 15:43:41 CEST 2026
docker.client.strategy=org.testcontainers.dockerclient.UnixSocketClientProviderStrategy
ryuk.container.privileged=true
testcontainers.reuse.enable=false
